// <auto-generated />
using System;
using HendonInventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HendonInventoryAPI.Migrations
{
    [DbContext(typeof(HendonDb))]
    partial class HendonDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("HendonInventoryAPI.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HendonInventoryAPI.Models.EquipmentInUse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipmentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EventID");

                    b.ToTable("EquipmentIns");
                });

            modelBuilder.Entity("HendonInventoryAPI.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HendonInventoryAPI.Models.EquipmentInUse", b =>
                {
                    b.HasOne("HendonInventoryAPI.Models.Equipment", "Equipment")
                        .WithMany("EquipmentIns")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HendonInventoryAPI.Models.Event", "Event")
                        .WithMany("EquipmentIns")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("HendonInventoryAPI.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentIns");
                });

            modelBuilder.Entity("HendonInventoryAPI.Models.Event", b =>
                {
                    b.Navigation("EquipmentIns");
                });
#pragma warning restore 612, 618
        }
    }
}
